version: "3.9"

services:
  user-service:
    build:
      context: services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8181:8181"
    networks:
      - ehealth-microservices
    volumes:
      - ./services/user-service/:/app

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database

networks:
  ehealth-microservices:
