apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: ehealth-microservices-2024
build:
  local:
    push: false
  artifacts:
    - image: user-service
      bazel:
        target: //services/user-service:container.tar
    - image: patient-service
      bazel:
        target: //services/patient-service:container.tar
manifests:
  rawYaml:
    - k8s/*-service.yaml
    - k8s/postgres.yaml
    # - k8s/ingress.yaml
portForward:
  - resourceType: service
    resourceName: k8s-patient-service
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: k8s-user-service
    port: 80
    localPort: 8081
