apiVersion: apps/v1
kind: Deployment
metadata:
  name: firebase-auth-emulator
spec:
  selector:
    matchLabels:
      app: firebase-auth-emulator
  template:
    metadata:
      labels:
        app: firebase-auth-emulator
    spec:
      containers:
        - name: firebase-auth
          image: andreysenov/firebase-tools:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo '{"emulators":{"auth":{"host":"0.0.0.0","port":9099},"hub":{"host":"0.0.0.0","port":4400},"ui":{"enabled":true,"host":"0.0.0.0","port":4000}}}' > firebase.json && \
              firebase emulators:start --project ehealth-local-project
          ports:
            - containerPort: 9099
            - containerPort: 4000
            - containerPort: 4400
---
apiVersion: v1
kind: Service
metadata:
  name: firebase-auth
spec:
  type: NodePort
  selector:
    app: firebase-auth-emulator
  ports:
    - name: auth
      port: 9099
      targetPort: 9099
      nodePort: 30099
    - name: ui
      port: 4000
      targetPort: 4000
      nodePort: 30004
    - name: hub
      port: 4400
      targetPort: 4400
      nodePort: 30440
