load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "users",
    srcs = [
        "controller.go",
        "service.go",
    ],
    importpath = "github.com/cloutstrife13/ehealth-microservices-2024/services/auth-service/src/users",
    visibility = ["//visibility:public"],
    deps = [
        "//packages/helpers",
        "//packages/models",
        "@com_github_labstack_echo//:echo",
    ],
)

alias(
    name = "go_default_library",
    actual = ":users",
    visibility = ["//visibility:public"],
)
